class Variable:
    """
    Base class for variables that can generate random values and undergo
    mutations.

    Attributes
    ----------
    None

    Methods
    -------
    random() -> any:
        Generates a random value for the variable.
    mutate(base_value: any) -> any:
        Mutates the given base value by applying some transformation.
    """

    def random(self) -> any:
        """
        Generates a random value for the variable.

        Returns
        -------
        any
            A randomly generated value of type 'any'. The actual type depends
            on the subclass implementation.

        Raises
        ------
        NotImplementedError
            If this method is not implemented in a subclass.
        """

        raise NotImplementedError("Base class.")

    def mutate(self, base_value: any) -> any:
        """
        Mutates the given base value by applying some transformation.

        Parameters
        ----------
        base_value : any
            The original value to be mutated. The type should match the
            expected input for the subclass implementation.

        Returns
        -------
        any
            A new value generated by mutating the base value. The actual type
            depends on the subclass implementation.

        Raises
        ------
        NotImplementedError
            If this method is not implemented in a subclass.
        """

        raise NotImplementedError("Base class.")
