from random import randint
from typing import Iterable


class Variable:
    """
    Base class for variables that can generate random values and undergo
    mutations.

    Attributes
    ----------
    None

    Methods
    -------
    random() -> any:
        Generates a random value for the variable.
    mutate(base_value: any) -> any:
        Mutates the given base value by applying some transformation.
    """

    def random(self) -> any:
        """
        Generates a random value for the variable.

        Returns
        -------
        any
            A randomly generated value of type 'any'. The actual type depends
            on the subclass implementation.

        Raises
        ------
        NotImplementedError
            If this method is not implemented in a subclass.
        """

        raise NotImplementedError("Base class.")

    def mutate(self, base_value: any) -> any:
        """
        Mutates the given base value by applying some transformation.

        Parameters
        ----------
        base_value : any
            The original value to be mutated. The type should match the
            expected input for the subclass implementation.

        Returns
        -------
        any
            A new value generated by mutating the base value. The actual type
            depends on the subclass implementation.

        Raises
        ------
        NotImplementedError
            If this method is not implemented in a subclass.
        """

        raise NotImplementedError("Base class.")


def apply_mutation(
        variables: Iterable[Variable],
        values: Iterable[any]
     ) -> Iterable[any]:
    """
    Applies mutation to a randomly selected value from the given list of
    values, using the corresponding variable's mutation method.

    Parameters
    ----------
    variables : Iterable[Variable]
        A collection of Variable objects that define how each corresponding
        value in 'values' can be mutated.
    values : Iterable[np.ndarray]
        A collection of values to which mutation may be applied. The length
        and order should match those of 'variables'.

    Returns
    -------
    Iterable[np.ndarray]
        A new list of values where one value has been potentially mutated.

    Notes
    -----
    This function makes a copy of the input 'values' list before applying the
    mutation, ensuring that the original list remains unchanged.
    """

    to_change = randint(0, len(values) - 1)
    new_values = values[:]
    new_values[to_change] = variables[to_change].mutate(new_values[to_change])
    return new_values
