from random import uniform
from typing import Optional

from ._variable import Variable


class Float(Variable):
    """
    A class for representing a floating-point variable that can generate
    random values within a specified range and mutate those values.

    Attributes
    ----------
    min_val : float
        The minimum possible value of the variable.
    max_val : float
        The maximum possible value of the variable.
    restrict : bool, optional
        A flag indicating whether to enforce that generated or mutated values
        remain within the [min_val, max_val] range. Default is True.

    Methods
    -------
    random() -> float:
        Generates a random float value within the defined range.
    mutate(base_value: float) -> float:
        Mutates a given float base value by adding a random perturbation and
        optionally restricting it to the defined range.
    """

    def __init__(self, min_val: float, max_val: float,
                 restrict: Optional[bool] = True):
        """
        Initializes a FloatVariable with specified minimum and maximum values,
        and an optional restriction flag.

        Parameters
        ----------
        min_val : float
            The minimum possible value of the variable.
        max_val : float
            The maximum possible value of the variable.
        restrict : bool, optional
            A flag indicating whether to enforce that generated or mutated
            values remain within the [min_val, max_val] range. Default is True.
        """

        self.min_val = min_val
        self.max_val = max_val
        self.restrict = restrict

    def random(self) -> float:
        """
        Generates a random float value within the defined range.

        Returns
        -------
        float
            A randomly generated float value between 'min_val' and 'max_val'.
        """

        return self.min_val + uniform(0, 1) * (self.max_val - self.min_val)

    def mutate(self, base_value: float) -> float:
        """
        Mutates a given float base value by adding a random perturbation and
        optionally restricting it to the defined range.

        Parameters
        ----------
        base_value : float
            The original float value to be mutated.

        Returns
        -------
        float
            A new float value generated by mutating the base value. If
            'restrict' is True, this value will be clamped between 'min_val'
            and 'max_val'.
        """

        new_value = base_value + uniform(-1, 1) * (base_value - self.random())
        if self.restrict:
            new_value = max(new_value, self.min_val)
            new_value = min(new_value, self.max_val)
        return new_value
