from random import uniform
from typing import Optional

from ._variable import Variable


class Integer(Variable):
    """
    A class for representing an integer variable that can generate random
    values within a specified range and mutate those values.

    Attributes
    ----------
    min_val : float
        The minimum possible value of the variable.
    max_val : float
        The maximum possible value of the variable.
    restrict : bool, optional
        A flag indicating whether to enforce that generated or mutated values
        remain within the [min_val, max_val] range. Default is True.

    Methods
    -------
    random() -> float:
        Generates a random integer value within the defined range.
    mutate(base_value: float) -> float:
        Mutates a given integer base value by adding a random perturbation and
        optionally restricting it to the defined range.
    """

    def __init__(self, min_val: int, max_val: int,
                 restrict: Optional[bool] = True):
        """
        Initializes an IntegerVariable with specified minimum and maximum
        values, and an optional restriction flag.

        Parameters
        ----------
        min_val : int
            The minimum possible value of the variable.
        max_val : int
            The maximum possible value of the variable.
        restrict : bool, optional
            A flag indicating whether to enforce that generated or mutated
            values remain within the [min_val, max_val] range. Default is True.
        """

        self.min_val = min_val
        self.max_val = max_val
        self.restrict = restrict

    def random(self) -> int:
        """
        Generates a random integer value within the defined range.

        Returns
        -------
        int
            A randomly generated integer value between 'min_val' and 'max_val'.
        """

        return int(self.min_val + uniform(0, 1) *
                   (self.max_val - self.min_val))

    def mutate(self, base_value: int) -> int:
        """
        Mutates a given integer base value by adding a random perturbation and
        optionally restricting it to the defined range.

        Parameters
        ----------
        base_value : int
            The original integer value to be mutated.

        Returns
        -------
        int
            A new integer value generated by mutating the base value. If
            'restrict' is True, this value will be clamped between 'min_val'
            and 'max_val'.
        """

        new_value = base_value + uniform(-1, 1) * (base_value - self.random())
        if self.restrict:
            new_value = max(new_value, self.min_val)
            new_value = min(new_value, self.max_val)
        return int(new_value)
